- name: vars from outside yaml files
  hosts: local
  connection: local
  vars_files:
  - emp_details.yaml
  tasks:
  - name: print name
    ansible.builtin.debug:
      msg: "Hello, my name {{ NAME }}"