- name: print msg
  hosts: local
  become: yes
  tasks:
  # - name: installing nginx
  #   ansible.builtin.package:
  #     name: nginx
  #     state: present
  - name: stopping the nginx
    ansible.builtin.service:
      name: nginx
      state: stopped