- name: vars practice
  hosts: local
  connection: local
  vars:
    Name: "Reddy"
    AGE: "30"
  tasks:
    - name: details of emp
      vars:
        Name: "Veni"
        ansible.builtin.debug:
          msg: "emp name: {{ Name }} and age is {{ AGE }}"