- name: play level vars
  hosts: local
  connection: local
  vars:
    Name: "Reddy"
    AGE: "30"
  tasks:
    - name: task level vars
      vars:
        Name: "Veni"
      ansible.builtin.debug:
        msg: "emp name: {{ Name }} and age is {{ AGE }}"